# https://github.com/chenyme/grok2api/blob/main/docker-compose.yml
services:
  grok2api:
    container_name: grok2api
    image: ghcr.io/chenyme/grok2api:latest
    # ports:
    #   - "58193:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: Asia/Shanghai
      LOG_LEVEL: DEBUG
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8000
      SERVER_WORKERS: 2
      SERVER_STORAGE_TYPE: local
      # 启用 CF 自动刷新: 取消以下三行注释，并取消底部 flaresolverr 服务的注释
      # FLARESOLVERR_URL: http://flaresolverr:8191
      # CF_REFRESH_INTERVAL: "600"
      # CF_TIMEOUT: "60"
    command:
      - sh
      - -c
      - >
        granian --interface asgi --host "$${SERVER_HOST:-0.0.0.0}"
        --port "$${SERVER_PORT:-8000}" --workers "$${SERVER_WORKERS:-1}" main:app
    volumes:
      - /home/ubuntu/docker/grok2api/data:/app/data
    restart: unless-stopped

    networks:
      - default

networks:
  default:
    external: true
    name: network_default
    
