services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      # ⚠️ 注意：需要修改密码
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: app

      TZ: Asia/Shanghai
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: '--data-checksums -E UTF8'

    volumes:
      - /home/ubuntu/docker/database/postgres/data:/var/lib/postgresql/data
      - /home/ubuntu/docker/database/postgres/conf:/etc/postgresql

    ports:
      - '55432:5432'

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - default

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    environment:
      TZ: Asia/Shanghai

    volumes:
      - /home/ubuntu/docker/database/redis/data:/data
      - /home/ubuntu/docker/database/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf:ro

    ports:
      - '56379:6379'

    command: ['redis-server', '/usr/local/etc/redis/redis.conf']

    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    networks:
      - default

networks:
  default:
    external: true
    name: network_default
